#di-muon tests#cmsRun runDiMuonDataAug06Tree_RA2.py         >& aug06.dimuon.out&
#di-muon tests#cmsRun runDiMuonDataAug24Tree_RA2.py	     >& aug24.dimoun.out&
#di-muon tests#cmsRun runDiMuonDataJul13Tree_RA2.py	     >& jul13.dimuon.out&
#di-muon tests#cmsRun runDiMuonDataPromptTree_RA2.py	     >& promp.dimuon.out&
#di-muon tests#cmsRun runDiMuonMC200Tree_RA2.py	     >& dimuon.200.out&
#di-muon tests#cmsRun runDiMuonMC400Tree_RA2.py	     >& dimuon.400.out&
#di-muon tests#cmsRun runDiMuonTTJetsSemiLepMCTree_RA2.py   >& dimuon.ttjets.out&
#photon tests#cmsRun runPhoton200MCTree_RA2.py	     >& gjets.200.out&
#photon tests#cmsRun runPhoton400MCTree_RA2.py	     >& gjets.400.out&
#photon tests#cmsRun runPhotonDataAug06Tree_RA2.py	     >& aug06.photon.out&
#photon tests#cmsRun runPhotonDataAug24Tree_RA2.py	     >& aug24.photon.out&
#photon tests#cmsRun runPhotonDataJul13Tree_RA2.py	     >& jul13.photon.out&
#photon tests#cmsRun runPhotonDataPromptTree_RA2.py	     >& promp.photon.out&
#photon tests#cmsRun runPhotonTTJetsSemiLepMCTree_RA2.py   >& photon.ttjets.out&
#photon tests#cmsRun runPhotonWJets400MCTree_RA2.py	     >& photon.wjets.out&
#photon tests#cmsRun runQCDPhoton1000ToInfMCTree_RA2.py    >& qcd.1000.out&
#photon tests#cmsRun runQCDPhoton250To500MCTree_RA2.py     >& qcd.250.out&
#photon tests#cmsRun runQCDPhoton500To1000MCTree_RA2.py    >& qcd.500.out&
#zinv tests#cmsRun runZInv200MCTree_RA2.py		     >& zinv.200.out&
#zinv tests#cmsRun runZInv400MCTree_RA2.py               >& zinv.400.out&
