import FWCore.ParameterSet.Config as cms

photonTree = cms.EDAnalyzer('RA2ZInvPhotonTreeMaker',
                          Debug           = cms.bool(False),
                          DebugString     = cms.string("photonTree"),
                          Data            = cms.bool(True),
                          ScaleFactor     = cms.double(1.),
                          PhotonSrc       = cms.InputTag("patPhotonsID"),
                          LoosePhotonSrc  = cms.InputTag("patPhotonsIDPFIsoLoose"),
                          TightPhotonSrc  = cms.InputTag("patPhotonsIDPFIsoTight"),
                          CombIsoR03PhotonSrc= cms.InputTag("patPhotonsIDCombIsoR03"),
                          CombIsoR04PhotonSrc= cms.InputTag("patPhotonsIDCombIsoR04"),
                          VertexSrc       = cms.InputTag("goodVertices"),
                          JetSrc          = cms.InputTag("patJetsPFNoPhotonIDSpecialPt30"),
                          htJetSrc        = cms.InputTag("patJetsPFNoPhotonIDSpecialPt50Eta25"),
                          bJetSrc         = cms.InputTag("patCSVMJetsPFNoPhotonIDSpecialPt30Eta24"),
                          htSource        = cms.InputTag("htPFchsNoPhotID"),
                          mhtSource       = cms.InputTag("mhtPFchsNoPhotID"),
                          metSource       = cms.InputTag("patMETsPF"),
                          TriggerResults  = cms.InputTag("hltTriggerSummaryAOD"),
                          runTopTagger    = cms.bool(False),
                          topTaggerSource = cms.string("topTagger"),
                          DoPUReweight    = cms.bool(False),
                          PUWeightSource    = cms.InputTag("puWeight"   ,"weight"),
                          EventWeightSource = cms.InputTag("eventWeight","weight"),

                          storeExtraVetos    = cms.bool(False),
                          electronVetoSource = cms.InputTag("electronVeto"),
                          muonVetoSource     = cms.InputTag("muonVeto"),
                          tauVetoSource      = cms.InputTag("tauVeto"),
                          isoTrkVetoSource   = cms.InputTag("isoTrkVeto"),
)

dimuonTree = cms.EDAnalyzer('RA2ZInvDiMuonTreeMaker',
                          Debug           = cms.bool(False),
                          Data            = cms.bool(True),
                          ScaleFactor     = cms.double(1.),
                          MuonSrc         = cms.InputTag("specialMuonCollection"),
                          VertexSrc       = cms.InputTag("goodVertices"),
                          JetSrc          = cms.InputTag("patJetsPFNoMuonPt30"),
                          htJetSrc        = cms.InputTag("patJetsPFNoMuonPt50Eta25"),
                          bJetSrc         = cms.InputTag("patCSVMJetsPFNoMuonPt30Eta24"),
                          htSource        = cms.InputTag("htPFchsNoMuon"),
                          mhtSource       = cms.InputTag("mhtPFchsNoMuon"),
                          metSource       = cms.InputTag("pfType1MetNoMuon","pfcand"),
                          TriggerResults  = cms.InputTag("hltTriggerSummaryAOD"),
                          runTopTagger    = cms.bool(False),
                          topTaggerSource = cms.string("topTaggerType3"),
                          DoPUReweight    = cms.bool(False),
                          PUWeightSource    = cms.InputTag("puWeight"   ,"weight"),
                          EventWeightSource = cms.InputTag("eventWeight","weight"),

                          storeExtraVetos    = cms.bool(False),
                          electronVetoSource = cms.InputTag("electronVeto"),
                          muonVetoSource     = cms.InputTag("muonVeto"),
                          tauVetoSource      = cms.InputTag("tauVeto"),
                          isoTrkVetoSource   = cms.InputTag("isoTrkVeto"),
)

dielectronTree = cms.EDAnalyzer('RA2ZInvDiElectronTreeMaker',
                          Debug           = cms.bool(False),
                          Data            = cms.bool(True),
                          ScaleFactor     = cms.double(1.),
                          ElectronSrc     = cms.InputTag("specialElectronCollection"),
                          VertexSrc       = cms.InputTag("goodVertices"),
                          JetSrc          = cms.InputTag("patJetsPFNoElectronPt30"),
                          htJetSrc        = cms.InputTag("patJetsPFNoElectronPt50Eta25"),
                          bJetSrc         = cms.InputTag("patCSVMJetsPFNoElectronPt30Eta24"),
                          htSource        = cms.InputTag("htPFchsNoElectron"),
                          mhtSource       = cms.InputTag("mhtPFchsNoElectron"),
                          metSource       = cms.InputTag("patMETsPF"),
                          TriggerResults  = cms.InputTag("hltTriggerSummaryAOD"),
                          runTopTagger    = cms.bool(False),
                          topTaggerSource = cms.string("topTaggerType3"),
                          DoPUReweight    = cms.bool(False),
                          PUWeightSource    = cms.InputTag("puWeight"   ,"weight"),
                          EventWeightSource = cms.InputTag("eventWeight","weight"),

                          storeExtraVetos    = cms.bool(False),
                          electronVetoSource = cms.InputTag("electronVeto"),
                          muonVetoSource     = cms.InputTag("muonVeto"),
                          tauVetoSource      = cms.InputTag("tauVeto"),
                          isoTrkVetoSource   = cms.InputTag("isoTrkVeto"),
)

zvvTree = cms.EDAnalyzer('RA2ZInvTreeMaker',
                          Debug           = cms.bool(False),
                          ScaleFactor     = cms.double(1.),
                          genLabel        = cms.InputTag("zinvBkgdst3ZBosons"),
                          VertexSrc       = cms.InputTag("goodVertices"),
                          JetSrc          = cms.InputTag("patJetsPFchsPt30"),
                          htJetSrc        = cms.InputTag("patJetsPFchsPt50Eta25"),
                          bJetSrc         = cms.InputTag("patCSVMJetsPFPt30Eta24"),
                          htSource        = cms.InputTag("htPFchs"),
                          mhtSource       = cms.InputTag("mhtPFchs"),
                          metSource       = cms.InputTag("patMETsPF"),
                          runTopTagger    = cms.bool(False),
                          topTaggerSource = cms.string("topTaggerType3"),
                          DoPUReweight    = cms.bool(True),
                          PUWeightSource    = cms.InputTag("puWeight"   ,"weight"),
                          EventWeightSource = cms.InputTag("eventWeight","weight"),

                          storeExtraVetos    = cms.bool(False),
                          electronVetoSource = cms.InputTag("electronVeto"),
                          muonVetoSource     = cms.InputTag("muonVeto"),
                          tauVetoSource      = cms.InputTag("tauVeto"),
                          isoTrkVetoSource   = cms.InputTag("isoTrkVeto"),
)
