import FWCore.ParameterSet.Config as cms

photonTree = cms.EDAnalyzer('RA2ZInvPhotonTreeMaker',
                          Debug           = cms.bool(False),
                          DebugString     = cms.string("photonID"),
                          Data            = cms.bool(True),
                          ScaleFactor     = cms.double(1.),
                          PhotonSrc       = cms.InputTag("patPhotonsID"),
                          TightPhotonSrc  = cms.InputTag("patPhotonsIDPFIso"),
                          VertexSrc       = cms.InputTag("goodVertices"),
                          JetSrc          = cms.InputTag("patJetsPFNoPhotonIDSpecialPt30"),
                          htJetSrc        = cms.InputTag("patJetsPFNoPhotonIDSpecialPt50Eta25"),
                          bJetSrc         = cms.InputTag("patCSVMJetsPFNoPhotonIDSpecialPt30Eta24"),
                          htSource        = cms.InputTag("htPFchsNoPhotID"),
                          mhtSource       = cms.InputTag("mhtPFchsNoPhotID"),
                          ra2HTSource     = cms.InputTag("htPFchs"),
                          ra2MHTSource    = cms.InputTag("mhtPFchs"),
                          TriggerResults  = cms.InputTag("hltTriggerSummaryAOD"),
                          DoPUReweight    = cms.bool(False),
                          PUWeightSource    = cms.InputTag("puWeight"   ,"weight"),
                          EventWeightSource = cms.InputTag("eventWeight","weight"),

                          computeMET = cms.bool(False),
                          metSource       = cms.InputTag("pfType1MetNoPhotID","pfcand"),
                          ra2METSource    = cms.InputTag("newMETwPhiCorr"),

                            ##objects for the gen study
                          runGenStudy = cms.bool(False),
                          genSrc      = cms.InputTag("genParticles"),
                          maxDR       = cms.double(0.2),
                          genJetSrc   = cms.InputTag("ak5GenJets"),
                          ra2JetSrc   = cms.InputTag("patJetsPFchsPt30"),
                          genMETSrc   = cms.InputTag("genMetTrue"),

                          storeExtraVetos    = cms.bool(False),
                          ra2ElectronForVeto = cms.InputTag("patElectronsIDIso"),
                          ra2MuonForVeto     = cms.InputTag("patMuonsPFIDIso"),
                          electronVetoSource = cms.InputTag("electronVeto"),
                          muonVetoSource     = cms.InputTag("muonVeto"),
                          isoTrkVetoSource   = cms.InputTag("isoTrkVeto"),
)

dimuonTree = cms.EDAnalyzer('RA2ZInvDiMuonTreeMaker',
                          Debug           = cms.bool(False),
                          Data            = cms.bool(True),
                          ScaleFactor     = cms.double(1.),
                          MuonSrc         = cms.InputTag("specialMuonCollection"),
                          VertexSrc       = cms.InputTag("goodVertices"),
                          JetSrc          = cms.InputTag("patJetsPFNoMuonPt30"),
                          htJetSrc        = cms.InputTag("patJetsPFNoMuonPt50Eta25"),
                          bJetSrc         = cms.InputTag("patCSVMJetsPFNoMuonPt30Eta24"),
                          htSource        = cms.InputTag("htPFchsNoMuon"),
                          mhtSource       = cms.InputTag("mhtPFchsNoMuon"),
                          metSource       = cms.InputTag("pfType1MetNoMuon","pfcand"),
                          ra2HTSource     = cms.InputTag("htPFchs"),
                          ra2MHTSource    = cms.InputTag("mhtPFchs"),
                          ra2METSource    = cms.InputTag("newMETwPhiCorr"),
                          TriggerResults  = cms.InputTag("hltTriggerSummaryAOD"),
                          runTopTagger    = cms.bool(False),
                          topTaggerSource = cms.string("topTaggerType3"),
                          DoPUReweight    = cms.bool(False),
                          PUWeightSource    = cms.InputTag("puWeight"   ,"weight"),
                          EventWeightSource = cms.InputTag("eventWeight","weight"),

                          storeExtraVetos    = cms.bool(False),
                          ra2ElectronForVeto = cms.InputTag("patElectronsIDIso"),
                          ra2MuonForVeto     = cms.InputTag("patMuonsPFIDIso"),
                          electronVetoSource = cms.InputTag("electronVeto"),
                          muonVetoSource     = cms.InputTag("muonVeto"),
                          isoTrkVetoSource   = cms.InputTag("isoTrkVeto"),
)

dielectronTree = cms.EDAnalyzer('RA2ZInvDiElectronTreeMaker',
                          Debug           = cms.bool(False),
                          Data            = cms.bool(True),
                          ScaleFactor     = cms.double(1.),
                          ElectronSrc     = cms.InputTag("specialElectronCollection"),
                          VertexSrc       = cms.InputTag("goodVertices"),
                          JetSrc          = cms.InputTag("patJetsPFNoElectronPt30"),
                          htJetSrc        = cms.InputTag("patJetsPFNoElectronPt50Eta25"),
                          bJetSrc         = cms.InputTag("patCSVMJetsPFNoElectronPt30Eta24"),
                          htSource        = cms.InputTag("htPFchsNoElectron"),
                          mhtSource       = cms.InputTag("mhtPFchsNoElectron"),
                          metSource       = cms.InputTag("pfType1MetNoElectron","pfcand"),
                          ra2HTSource     = cms.InputTag("htPFchs"),
                          ra2MHTSource    = cms.InputTag("mhtPFchs"),
                          ra2METSource    = cms.InputTag("newMETwPhiCorr"),
                          TriggerResults  = cms.InputTag("hltTriggerSummaryAOD"),
                          runTopTagger    = cms.bool(False),
                          topTaggerSource = cms.string("topTaggerType3"),
                          DoPUReweight    = cms.bool(False),
                          PUWeightSource    = cms.InputTag("puWeight"   ,"weight"),
                          EventWeightSource = cms.InputTag("eventWeight","weight"),

                          storeExtraVetos    = cms.bool(False),
                          ra2ElectronForVeto = cms.InputTag("patElectronsIDIso"),
                          ra2MuonForVeto     = cms.InputTag("patMuonsPFIDIso"),
                          electronVetoSource = cms.InputTag("electronVeto"),
                          muonVetoSource     = cms.InputTag("muonVeto"),
                          isoTrkVetoSource   = cms.InputTag("isoTrkVeto"),
)

zvvTree = cms.EDAnalyzer('RA2ZInvTreeMaker',
                          Debug           = cms.bool(False),
                          ScaleFactor     = cms.double(1.),
                          genLabel        = cms.InputTag("zinvBkgdst3ZBosons"),
                          genSrc          = cms.InputTag("zinvBkgdst3ZBosons"),
                          genJetSrc       = cms.InputTag("ak5GenJets"),
                          genMETSrc       = cms.InputTag("genMetTrue"),
                          VertexSrc       = cms.InputTag("goodVertices"),
                          JetSrc          = cms.InputTag("patJetsPFchsPt30"),
                          htJetSrc        = cms.InputTag("patJetsPFchsPt50Eta25"),
                          bJetSrc         = cms.InputTag("patCSVMJetsPFPt30Eta24"),
                          htSource        = cms.InputTag("htPFchs"),
                          mhtSource       = cms.InputTag("mhtPFchs"),
                          metSource       = cms.InputTag("newMETwPhiCorr"),
                          runTopTagger    = cms.bool(False),
                          topTaggerSource = cms.string("topTaggerType3"),
                          DoPUReweight    = cms.bool(True),
                          PUWeightSource    = cms.InputTag("puWeight"   ,"weight"),
                          EventWeightSource = cms.InputTag("eventWeight","weight"),

                          storeExtraVetos    = cms.bool(False),
                          ra2ElectronForVeto = cms.InputTag("patElectronsIDIso"),
                          ra2MuonForVeto     = cms.InputTag("patMuonsPFIDIso"),
                          electronVetoSource = cms.InputTag("electronVeto"),
                          muonVetoSource     = cms.InputTag("muonVeto"),
                          isoTrkVetoSource   = cms.InputTag("isoTrkVeto"),
)
