import FWCore.ParameterSet.Config as cms

photonTree = cms.EDAnalyzer('RA2ZInvPhotonTreeMaker',
                          Debug           = cms.bool(False),
                          Data            = cms.bool(True),
                          ScaleFactor     = cms.double(1.),
                          PhotonSrc       = cms.InputTag("patPhotonsID"),
                          VertexSrc       = cms.InputTag("goodVertices"),
                          JetSrc          = cms.InputTag("patJetsPFNoPhotonIDSpecialPt30"),
                          htJetSrc        = cms.InputTag("patJetsPFNoPhotonIDSpecialPt50Eta25"),
                          bJetSrc         = cms.InputTag("patCSVMJetsPFNoPhotonIDSpecialPt30Eta24"),
                          htSource        = cms.InputTag("htPFchsNoPhotID"),
                          mhtSource       = cms.InputTag("mhtPFchsNoPhotID"),
                          metSource       = cms.InputTag("patMETsPF"),
                          topTaggerSource = cms.string("topTagger"),
                          DoPUReweight    = cms.bool(False),
                          PUWeightSource    = cms.InputTag("puWeight"   ,"weight"),
                          EventWeightSource = cms.InputTag("eventWeight","weight"),
)

dimuonTree = cms.EDAnalyzer('RA2ZInvDiMuonTreeMaker',
                          Debug           = cms.bool(False),
                          Data            = cms.bool(True),
                          ScaleFactor     = cms.double(1.),
                          MuonSrc         = cms.InputTag("specialMuonCollection"),
                          VertexSrc       = cms.InputTag("goodVertices"),
                          JetSrc          = cms.InputTag("patJetsPFNoMuonPt30"),
                          htJetSrc        = cms.InputTag("patJetsPFNoMuonPt50Eta25"),
                          bJetSrc         = cms.InputTag("patCSVMJetsPFNoMuonPt30Eta24"),
                          htSource        = cms.InputTag("htPFchsNoMuon"),
                          mhtSource       = cms.InputTag("mhtPFchsNoMuon"),
                          metSource       = cms.InputTag("patMETsPF"),
                          topTaggerSource = cms.string("topTaggerType3"),
                          DoPUReweight    = cms.bool(False),
                          PUWeightSource    = cms.InputTag("puWeight"   ,"weight"),
                          EventWeightSource = cms.InputTag("eventWeight","weight"),
)

zvvTree = cms.EDAnalyzer('RA2ZInvTreeMaker',
                          Debug           = cms.bool(False),
                          ScaleFactor     = cms.double(1.),
                          genLabel        = cms.InputTag("zinvBkgdst3ZBosons"),
                          VertexSrc       = cms.InputTag("goodVertices"),
                          JetSrc          = cms.InputTag("patJetsPFchsPt30"),
                          htJetSrc        = cms.InputTag("patJetsPFchsPt50Eta25"),
                          bJetSrc         = cms.InputTag("patCSVMJetsPFPt30Eta24"),
                          htSource        = cms.InputTag("htPFchs"),
                          mhtSource       = cms.InputTag("mhtPFchs"),
                          metSource       = cms.InputTag("patMETsPF"),
                          topTaggerSource = cms.string("topTaggerType3"),
                          DoPUReweight    = cms.bool(True),
                          PUWeightSource    = cms.InputTag("puWeight"   ,"weight"),
                          EventWeightSource = cms.InputTag("eventWeight","weight"),
)
